hostname: go.sohi.link
paths:

  # For example, this will allow `go get go.sohi.link/demo` to find the demo package in this repo
  - path: /demo
    repoRoot: https://github.com/jashandeep-sohi/go.sohi.link
    vcs: git
    home: https://github.com/jashandeep-sohi/go.sohi.link
    directory: https://github.com/jashandeep-sohi/go.sohi.link/tree/master{/dir}
    file: https://github.com/jashandeep-sohi/go.sohi.link/blob/master{/dir}/{file}#L{line}
