name = "go-vanity"
type = "webpack"
webpack_config = "webpack.config.js"

# Set via env CF_ACCOUNT_ID
account_id = ""
workers_dev = true

[env.prod]
# Set via env CF_ZONE_ID
zone_id = ""
route = "go.sohi.link/*"
