name: Deploy

on:
  push:
    branches:
      - default
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: 
      name: prod
      url: https://go.sohi.link/
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: prod
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
